channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.5.0
  - appnope=0.1.0
  - astor=0.7.1
  - backcall=0.1.0
  - blas=1.1
  - bleach=1.5.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2019.11.28
  - certifi=2018.8.24
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.2.3
  - freetype=2.8.1
  - gast=0.3.2
  - graphviz=2.38.0
  - grpcio=1.14.1
  - h5py=2.7.1
  - hdf5=1.10.1
  - html5lib=0.9999999
  - icu=58.2
  - ipykernel=4.8.1
  - ipython=7.0.1
  - ipython_genutils=0.2.0
  - ipywidgets=6.0.0
  - jedi=0.12.1
  - jinja2=2.10.3
  - jpeg=9c
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - keras=2.2.3
  - libcxx=9.0.0
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libgpuarray=0.7.6
  - libiconv=1.15
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libprotobuf=3.6.0
  - libsodium=1.0.18
  - libtiff=4.1.0
  - lz4-c=1.8.3
  - mako=1.1.0
  - markdown=3.1.1
  - markupsafe=1.0
  - matplotlib=2.1.2
  - mistune=0.8.3
  - mizani=0.4.6
  - nb_conda_kernels=2.1.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.0
  - numexpr=2.6.4
  - numpy=1.12.1
  - openblas=0.2.19
  - openssl=1.0.2t
  - palettable=3.3.0
  - pandas=0.22.0
  - pandoc=2.8.0.1
  - pandocfilters=1.4.2
  - parso=0.5.1
  - patsy=0.5.1
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=18.0
  - plotnine=0.3.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - protobuf=3.6.0
  - ptyprocess=0.6.0
  - pydot=1.2.3
  - pygments=2.5.2
  - pygpu=0.7.6
  - pyparsing=2.4.5
  - pyqt=5.6.0
  - python=3.5.5
  - python-dateutil=2.8.1
  - python-graphviz=0.8.4
  - pytz=2019.3
  - pyyaml=3.12
  - pyzmq=17.1.2
  - qt=5.6.2
  - qtconsole=4.6.0
  - readline=7.0
  - requests=2.12.5
  - scikit-learn=0.18.1
  - scipy=1.1.0
  - seaborn=0.8.1
  - send2trash=1.5.0
  - setuptools=40.4.3
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - sqlite=3.28.0
  - statsmodels=0.8.0
  - tensorboard=0.4.0rc3
  - tensorflow=1.4.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.4
  - theano=1.0.3
  - tk=8.6.10
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.32.0
  - widgetsnbextension=2.0.0
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - keras-tqdm==2.0.1
    - tqdm==4.40.0
